// Code generated by labsgen. DO NOT EDIT.

package labs

import (
	"log/slog"
	"strings"
	"sync"
)

// Feature name constants
const (
	FeatureGlobalRouter       = "globalrouter"
	FeatureDistributedRunners = "distributedrunners"
	FeatureUserSubdomains     = "usersubdomains"
	FeatureAdminAPI           = "adminapi"
	FeatureRouteOIDC          = "routeoidc"
)

// AllFeatures returns a list of all known feature names
func AllFeatures() []string {
	return []string{
		FeatureGlobalRouter,
		FeatureDistributedRunners,
		FeatureUserSubdomains,
		FeatureAdminAPI,
		FeatureRouteOIDC,
	}
}

// FeatureDescriptions returns a map of feature names to their descriptions
func FeatureDescriptions() map[string]string {
	return map[string]string{
		FeatureGlobalRouter:       "Use global NAT traversal router for connectivity",
		FeatureDistributedRunners: "Schedule jobs across multiple runner nodes",
		FeatureUserSubdomains:     "Allow claiming custom subdomains",
		FeatureAdminAPI:           "Enable the admin API for application management functions",
		FeatureRouteOIDC:          "Enable OIDC authentication for HTTP routes",
	}
}

var (
	mu              sync.RWMutex
	enabledFeatures = make(map[string]bool)
)

// featureDefaults holds the default state for each feature
var featureDefaults = map[string]bool{
	FeatureGlobalRouter:       false,
	FeatureDistributedRunners: false,
	FeatureUserSubdomains:     false,
	FeatureAdminAPI:           false,
	FeatureRouteOIDC:          false,
}

// Init initializes the labs feature flags from the provided flag strings.
// Each flag can be a feature name to enable it, or prefixed with "-" to disable it.
// Unknown feature names are logged as warnings but do not cause an error.
// This function should be called once at startup.
func Init(log *slog.Logger, flags []string) {
	mu.Lock()
	defer mu.Unlock()

	// Start with defaults
	for name, defaultVal := range featureDefaults {
		enabledFeatures[name] = defaultVal
	}

	for _, flag := range flags {
		flag = strings.TrimSpace(flag)
		if flag == "" {
			continue
		}

		disable := false
		name := flag
		if strings.HasPrefix(flag, "-") {
			disable = true
			name = strings.TrimPrefix(flag, "-")
		}

		// Normalize to lowercase for lookup
		name = strings.ToLower(name)

		// Check if it's a known feature
		if _, known := featureDefaults[name]; !known {
			if log != nil {
				log.Warn("unknown labs feature flag", "flag", flag)
			}
			continue
		}

		enabledFeatures[name] = !disable
		if log != nil {
			log.Info("labs feature configured", "feature", name, "enabled", !disable)
		}
	}
}

// Reset resets the feature flags to their default state.
// This is primarily useful for testing.
func Reset() {
	mu.Lock()
	defer mu.Unlock()

	enabledFeatures = make(map[string]bool)
	for name, defaultVal := range featureDefaults {
		enabledFeatures[name] = defaultVal
	}
}

// IsEnabled returns whether a feature is enabled.
// Returns the default value if Init has not been called.
func IsEnabled(name string) bool {
	mu.RLock()
	defer mu.RUnlock()

	name = strings.ToLower(name)
	if enabled, ok := enabledFeatures[name]; ok {
		return enabled
	}
	if defaultVal, ok := featureDefaults[name]; ok {
		return defaultVal
	}
	return false
}

// Feature predicate functions

// GlobalRouter returns whether the globalrouter feature is enabled.
// Use global NAT traversal router for connectivity
func GlobalRouter() bool {
	return IsEnabled(FeatureGlobalRouter)
}

// DistributedRunners returns whether the distributedrunners feature is enabled.
// Schedule jobs across multiple runner nodes
func DistributedRunners() bool {
	return IsEnabled(FeatureDistributedRunners)
}

// UserSubdomains returns whether the usersubdomains feature is enabled.
// Allow claiming custom subdomains
func UserSubdomains() bool {
	return IsEnabled(FeatureUserSubdomains)
}

// AdminAPI returns whether the adminapi feature is enabled.
// Enable the admin API for application management functions
func AdminAPI() bool {
	return IsEnabled(FeatureAdminAPI)
}

// RouteOIDC returns whether the routeoidc feature is enabled.
// Enable OIDC authentication for HTTP routes
func RouteOIDC() bool {
	return IsEnabled(FeatureRouteOIDC)
}
