package main

import (
	"bytes"
	"flag"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"text/template"

	"gopkg.in/yaml.v3"
)

var (
	featuresPath = flag.String("features", "", "Path to the features YAML file")
	outputDir    = flag.String("output", "", "Output directory for generated files")
)

type Feature struct {
	Name        string `yaml:"name"`
	Predicate   string `yaml:"predicate"`
	Description string `yaml:"description"`
	Default     bool   `yaml:"default"`
}

type FeaturesFile struct {
	Features []Feature `yaml:"features"`
}

func main() {
	flag.Parse()

	if *featuresPath == "" || *outputDir == "" {
		log.Fatal("Both -features and -output flags are required")
	}

	data, err := os.ReadFile(*featuresPath)
	if err != nil {
		log.Fatalf("Failed to read features file: %v", err)
	}

	var features FeaturesFile
	if err := yaml.Unmarshal(data, &features); err != nil {
		log.Fatalf("Failed to parse features YAML: %v", err)
	}

	if err := os.MkdirAll(*outputDir, 0755); err != nil {
		log.Fatalf("Failed to create output directory: %v", err)
	}

	content, err := generateLabsCode(&features)
	if err != nil {
		log.Fatalf("Failed to generate labs code: %v", err)
	}

	formatted, err := format.Source([]byte(content))
	if err != nil {
		debugPath := filepath.Join(*outputDir, "labs.gen.go.debug")
		os.WriteFile(debugPath, []byte(content), 0644)
		log.Fatalf("Failed to format labs.gen.go (debug output written to %s): %v", debugPath, err)
	}

	outPath := filepath.Join(*outputDir, "labs.gen.go")
	if err := os.WriteFile(outPath, formatted, 0644); err != nil {
		log.Fatalf("Failed to write labs.gen.go: %v", err)
	}

	log.Printf("Generated %s", outPath)
}

func generateLabsCode(features *FeaturesFile) (string, error) {
	tmpl, err := template.New("labs").Parse(labsTemplate)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, features); err != nil {
		return "", err
	}

	return buf.String(), nil
}

const labsTemplate = `// Code generated by labsgen. DO NOT EDIT.

package labs

import (
	"log/slog"
	"strings"
	"sync"
)

// Feature name constants
const (
{{- range .Features}}
	Feature{{.Predicate}} = "{{.Name}}"
{{- end}}
)

// AllFeatures returns a list of all known feature names
func AllFeatures() []string {
	return []string{
{{- range .Features}}
		Feature{{.Predicate}},
{{- end}}
	}
}

// FeatureDescriptions returns a map of feature names to their descriptions
func FeatureDescriptions() map[string]string {
	return map[string]string{
{{- range .Features}}
		Feature{{.Predicate}}: "{{.Description}}",
{{- end}}
	}
}

var (
	mu              sync.RWMutex
	enabledFeatures = make(map[string]bool)
)

// featureDefaults holds the default state for each feature
var featureDefaults = map[string]bool{
{{- range .Features}}
	Feature{{.Predicate}}: {{.Default}},
{{- end}}
}

// Init initializes the labs feature flags from the provided flag strings.
// Each flag can be a feature name to enable it, or prefixed with "-" to disable it.
// Unknown feature names are logged as warnings but do not cause an error.
// This function should be called once at startup.
func Init(log *slog.Logger, flags []string) {
	mu.Lock()
	defer mu.Unlock()

	// Start with defaults
	for name, defaultVal := range featureDefaults {
		enabledFeatures[name] = defaultVal
	}

	for _, flag := range flags {
		flag = strings.TrimSpace(flag)
		if flag == "" {
			continue
		}

		disable := false
		name := flag
		if strings.HasPrefix(flag, "-") {
			disable = true
			name = strings.TrimPrefix(flag, "-")
		}

		// Normalize to lowercase for lookup
		name = strings.ToLower(name)

		// Check if it's a known feature
		if _, known := featureDefaults[name]; !known {
			if log != nil {
				log.Warn("unknown labs feature flag", "flag", flag)
			}
			continue
		}

		enabledFeatures[name] = !disable
		if log != nil {
			log.Info("labs feature configured", "feature", name, "enabled", !disable)
		}
	}
}

// Reset resets the feature flags to their default state.
// This is primarily useful for testing.
func Reset() {
	mu.Lock()
	defer mu.Unlock()

	enabledFeatures = make(map[string]bool)
	for name, defaultVal := range featureDefaults {
		enabledFeatures[name] = defaultVal
	}
}

// IsEnabled returns whether a feature is enabled.
// Returns the default value if Init has not been called.
func IsEnabled(name string) bool {
	mu.RLock()
	defer mu.RUnlock()

	name = strings.ToLower(name)
	if enabled, ok := enabledFeatures[name]; ok {
		return enabled
	}
	if defaultVal, ok := featureDefaults[name]; ok {
		return defaultVal
	}
	return false
}

// Feature predicate functions
{{- range .Features}}

// {{.Predicate}} returns whether the {{.Name}} feature is enabled.
// {{.Description}}
func {{.Predicate}}() bool {
	return IsEnabled(Feature{{.Predicate}})
}
{{- end}}
`
